<a href="https://colab.research.google.com/github/Soumya78bhal/APPS/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=pd.read_csv('employees.csv')

In [ ]:
a.head(3)

   id     name department  salary  age       city
0   1    Alice         HR   50000   25      Delhi
1   2      Bob         IT   70000   30     Mumbai
2   3  Charlie    Finance   65000   28  Bangalore

In [ ]:
a.tail(3)

    id    name department  salary  age       city
22  23   Wendy         HR   59000   27  Bangalore
23  24  Xavier    Finance   74000   35      Delhi
24  25    Yara         IT   87000   36    Chennai

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          25 non-null     int64
 1   name        25 non-null     object
 2   department  25 non-null     object
 3   salary      25 non-null     int64
 4   age         25 non-null     int64
 5   city        25 non-null     object
dtypes: int64(3), object(3)
memory usage: 1.3+ KB

In [ ]:
a.describe()

              id        salary        age
count  25.000000     25.000000  25.000000
mean   13.000000  72320.000000  32.480000
std     7.359801  12986.274806   5.252936
min     1.000000  50000.000000  24.000000
25%     7.000000  61000.000000  28.000000
50%    13.000000  72000.000000  32.000000
75%    19.000000  83000.000000  36.000000
max    25.000000  95000.000000  42.000000

In [ ]:
a.loc[[1,2],['id','salary']]

   id  salary
1   2   70000
2   3   65000

In [ ]:
a.sort_values('salary',ascending=False)

    id     name department  salary  age       city
12  13     Mike         IT   95000   42    Chennai
18  19   Sophia         IT   92000   41  Bangalore
6    7    Grace         IT   90000   40  Bangalore
15  16     Paul         IT   88000   37      Delhi
24  25     Yara         IT   87000   36    Chennai
9   10     Jack         IT   85000   38     Mumbai
21  22   Victor         IT   83000   39     Mumbai
3    4    David         IT   80000   35      Delhi
14  15    Oscar    Finance   78000   36  Bangalore
20  21      Uma    Finance   76000   34    Chennai
8    9      Ian    Finance   75000   31      Delhi
23  24   Xavier    Finance   74000   35      Delhi
5    6    Frank    Finance   72000   32    Chennai
17  18     Ryan    Finance   71000   30     Mumbai
1    2      Bob         IT   70000   30     Mumbai
11  12      Leo    Finance   68000   29      Delhi
2    3  Charlie    Finance   65000   28  Bangalore
13  14     Nina         HR   62000   33     Mumbai
19  20      Tom         HR   61000   28      Delhi
7    8    Helen         HR   60000   29    Chennai
22  23    Wendy         HR   59000   27  Bangalore
10  11    Karen         HR   58000   26  Bangalore
4    5      Eve         HR   55000   27     Mumbai
16  17    Queen         HR   54000   24    Chennai
0    1    Alice         HR   50000   25      Delhi

In [ ]:
a.groupby('department')['salary'].mean()

department
Finance    72375.000000
HR         57375.000000
IT         85555.555556
Name: salary, dtype: float64